# Generated by Django 3.1.7 on 2021-03-25 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='occupied',
        ),
    ]
